### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by gazal-k**
Don't merge this before #2
More tests necessary

### CODE REVIEW

**Comment by Nemo64** [comment]
Are you interested in becoming a contributor on this repository? It seems that you put a lot effort into this... more than i currently do.

**Comment by gazal-k** [comment]
@Nemo64 thank you :smiley: that'd be great. We really do need this component at my company, so I will try to keep contributing.

**Comment by Nemo64** [comment]
@gazal-k I added you. ;) I don't seem to have a direct way to contact you but basically: every bugfix, test or meta change goes. I'd like to know about new features though.

**Comment by gazal-k** [comment]
you can find me on https://gitter.im/. And I will keep creating pull requests. Always good to get a second set of eyes on a change.

**Comment by gazal-k** [comment]
I think we'll merge this for now, we'll have to add more tests. I'll try to setup travis CI and a component page for the repo.

**Comment by gazal-k** [comment]
@Nemo64 I've setup travis ci config. I can't setup the build on the base repository though. I'm afraid you'll have to help me with that.

**Pull request merged**
